language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer install
  - ls vendor/matthiasnoback/symfony-dependency-injection-test/PhpUnit/AbstractExtensionTestCase.php
script: bin/phpunit Tests
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
