dist: trusty # for php 5.5 support
language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.4'

env:
  - SYMFONY_VERSION="2.1"
  - SYMFONY_VERSION="2.8"
  - SYMFONY_VERSION="3.4"

before_script:
  - php -d memory_limit=-1 `which composer` require symfony/framework-bundle:${SYMFONY_VERSION}
script: bin/phpunit --coverage-clover=coverage.clover Tests
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
