language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.4'

env:
  - SYMFONY_VERSION="2.1" CONSOLE_EXECUTABLE="app/console"
  - SYMFONY_VERSION="2.8" CONSOLE_EXECUTABLE="app/console"
  - SYMFONY_VERSION="3.4" CONSOLE_EXECUTABLE="bin/console"

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer update
  - ${CONSOLE_EXECUTABLE}
script: bin/phpunit --coverage-clover=coverage.clover Tests
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
