language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
before_script:
  - composer install
install:
  - composer require symfony/config:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/http-foundation:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/filesystem:${SYMFONY_VERSION}
script: bin/phpunit  --coverage-clover=coverage.clover Tests
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
