language: php

matrix:
  include:
    - php: 5.3
      SYMFONY_VERSION="2.1.*"
    - php: 5.3
      SYMFONY_VERSION="2.2.*"
    - php: 5.3
      SYMFONY_VERSION="2.3.*"
    - php: 5.3
      SYMFONY_VERSION="2.4.*"
    - php: 5.3
      SYMFONY_VERSION="2.5.*"
    - php: 5.3
      SYMFONY_VERSION="2.6.*"
    - php: 5.3
      SYMFONY_VERSION="2.7.*"
    - php: 5.3
      SYMFONY_VERSION="2.8.*"
  
    - php: 5.4
      SYMFONY_VERSION="2.1.*"
    - php: 5.4
      SYMFONY_VERSION="2.2.*"
    - php: 5.4
      SYMFONY_VERSION="2.3.*"
    - php: 5.4
      SYMFONY_VERSION="2.4.*"
    - php: 5.4
      SYMFONY_VERSION="2.5.*"
    - php: 5.4
      SYMFONY_VERSION="2.6.*"
    - php: 5.4
      SYMFONY_VERSION="2.7.*"
    - php: 5.4
      SYMFONY_VERSION="2.8.*"
  
    - php: 5.5
      SYMFONY_VERSION="2.1.*"
    - php: 5.5
      SYMFONY_VERSION="2.2.*"
    - php: 5.5
      SYMFONY_VERSION="2.3.*"
    - php: 5.5
      SYMFONY_VERSION="2.4.*"
    - php: 5.5
      SYMFONY_VERSION="2.5.*"
    - php: 5.5
      SYMFONY_VERSION="2.6.*"
    - php: 5.5
      SYMFONY_VERSION="2.7.*"
    - php: 5.5
      SYMFONY_VERSION="2.8.*"
    - php: 5.5
      SYMFONY_VERSION="3.0.*"
  
    - php: 5.6
      SYMFONY_VERSION="2.1.*"
    - php: 5.6
      SYMFONY_VERSION="2.2.*"
    - php: 5.6
      SYMFONY_VERSION="2.3.*"
    - php: 5.6
      SYMFONY_VERSION="2.4.*"
    - php: 5.6
      SYMFONY_VERSION="2.5.*"
    - php: 5.6
      SYMFONY_VERSION="2.6.*"
    - php: 5.6
      SYMFONY_VERSION="2.7.*"
    - php: 5.6
      SYMFONY_VERSION="2.8.*"
    - php: 5.6
      SYMFONY_VERSION="3.0.*"
  
    - php: 7.0
      SYMFONY_VERSION="2.1.*"
    - php: 7.0
      SYMFONY_VERSION="2.2.*"
    - php: 7.0
      SYMFONY_VERSION="2.3.*"
    - php: 7.0
      SYMFONY_VERSION="2.4.*"
    - php: 7.0
      SYMFONY_VERSION="2.5.*"
    - php: 7.0
      SYMFONY_VERSION="2.6.*"
    - php: 7.0
      SYMFONY_VERSION="2.7.*"
    - php: 7.0
      SYMFONY_VERSION="2.8.*"
    - php: 7.0
      SYMFONY_VERSION="3.0.*"

before_script:
  - composer install
install:
  - composer require symfony/config:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/http-foundation:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/filesystem:${SYMFONY_VERSION}
script: bin/phpunit  --coverage-clover=coverage.clover Tests
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
